<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_form"
 *
 * Auto generated by Extension Builder 2019-08-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RkwForm',
    'description' => 'Provides forms. With FormFramework support from Typo3 version 8.7.',
    'category' => 'plugin',
    'author' => 'Maximilian Fäßler, Steffen Kroggel, Christian Dilger',
    'author_email' => 'maximilian@faesslerweb.de, developer@steffenkroggel.de, c.dilger@addorange.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'clearCacheOnLoad' => 0,
    'version' => '9.5.10',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
            'core_extended' => '9.5.4-10.4.99',
            'fe_register' => '9.5.0-10.4.99',
            'postmaster' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
