services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RKW\RkwForm\:
    resource: '../Classes/*'

  RKW\RkwForm\Command\CleanupCommand:
    tags:
      - name: 'console.command'
        command: 'rkw_form:cleanup'
        schedulable: true
